apiVersion: v1
kind: Service
metadata:
  name: go-app
  namespace: go-app
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

    
# Traffic flow
# Internet → LoadBalancer (Port 80) → Service → Healthy Pods (Port 8080)
